# Copyright The Mumble Developers. All rights reserved.
# Use of this source code is governed by a BSD-style license
# that can be found in the LICENSE file at the root of the
# Mumble source tree or at <https://www.mumble.info/LICENSE>.

steps:
  - script: git submodule --quiet update --init --recursive
    displayName: 'Fetch submodules'
  - script: .ci/azure-pipelines/install-environment_linux.bash
    displayName: 'Install build environment'
  - script: .ci/azure-pipelines/build_linux.bash
    env:
      MUMBLE_BUILD_NUMBER_TOKEN: $(BUILD_NUMBER_TOKEN)
    displayName: 'Build'
  - script: 'cd $BUILD_BINARIESDIRECTORY; QT_QPA_PLATFORM=offscreen ctest --output-on-failure'
    displayName: 'Test'
# - script: .ci/azure-pipelines/package_AppImage.bash
#   displayName: 'Release'
# - template: task-publish-artifacts.yml
#   parameters:
#     name: "AppImage" 
