name: Publish to WinGet
on:
  release:
    types: [released]
  workflow_dispatch:
    inputs:
      tag:
        description: 'The release tag to publish'
        required: true

jobs:
  publish:
    runs-on: windows-latest
    steps:
      - name: Publish Mumble client
        uses: vedantmgoyal9/winget-releaser@main
        with:
          release-tag: ${{ github.event.release.tag_name || github.event.inputs.tag }}
          identifier: Mumble.Mumble.Client
          installers-regex: mumble_client.*\.exe$
          token: ${{ secrets.WINGET_TOKEN }}

      - name: Publish Mumble server
        uses: vedantmgoyal9/winget-releaser@main
        with:
          release-tag: ${{ github.event.release.tag_name || github.event.inputs.tag }}
          identifier: Mumble.Mumble.Server
          installers-regex: mumble_server.*\.exe$
          token: ${{ secrets.WINGET_TOKEN }}
